### ISSUE TITLE
`require_relative': cannot load AmineFace

### ISSUE THREAD

**Issue by jayleicn** [nagadomi/animeface-2009#1]
My ruby version `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`, gem version `2.6.8`, system `ubuntu-14.04`

Run `./build`, some make errors in the end
```
mv -f .deps/libnvxs_la-nv_laplacian.Tpo .deps/libnvxs_la-nv_laplacian.Plo
make[1]: *** No rule to make target `CLAPACK/liblapack_nvxs.a', needed by `libnvxs.la'.  Stop.
make[1]: Leaving directory `/home/jielei/project/notebooks/learn-pytorch/anime-GAN/animeface-2009/nvxs'
make: *** [install-recursive] Error 1
checking for nv_core.h... no 
error: Can't locate libnvxs
make: *** No targets specified and no makefile found.  Stop.
                            
                            
Check: % cd animeface-ruby
 % ruby sample.rb <input image>  
```

I simply ignored it, then run `ruby sample.rb image.png`, error occurs
```
sample.rb:3:in `require_relative': cannot load such file -- /my-path/animeface-2009/animeface-ruby/AnimeFace (LoadError)
        from sample.rb:3:in `<main>'
```

I have googled this kind of require errors and tried modifying `require_relative "AnimeFace" ` to `require_relative "animeface" `, which is not working. 

What's wrong with this? Thanks in advance for any help!

**Comment by nagadomi** [comment]
Sorry, it's due to a bug in the build script.
I fixed it now. Try rebuild.
```
git pull
./build.sh
```
