### ISSUE TITLE
Nothing to draw

### ISSUE THREAD

**Issue by goodmind** [nagadomi/animeface-2009#2]
I got this when using `sample.rb`
```sh
[]
sample.rb:48:in `draw': nothing to draw (ArgumentError)
        from sample.rb:48:in `<main>'
```

with this picture

![photo_2017-03-27_16-32-58](https://cloud.githubusercontent.com/assets/3275424/24357361/dd4547ba-1316-11e7-848e-8be1d1042177.jpg)

**Comment by nagadomi** [comment]
I fixed that error but the fundamental issue is that no faces were detected.
